10 PRINT "HELLO! LET'S PROGRAM IN BASIC."
15 PRINT
20 INPUT "WOULD YOU MIND TYPING IN YOUR NAME";A$
25 PRINT
30 PRINT "THANKS, ";A$;"! THIS WILL BE FUN!"
35 PRINT
40 INPUT "NOW TELL ME YOUR FAVORITE NUMBER";N
45 PRINT
50 PRINT "THAT'S A GOOD ONE! I LIKE";N^2;"MYSELF."
60 PRINT "NICE MEETING YOU, ";A$;"."
