/* Auto-generated by scripts/gen_sms_solarian_gfx.py -- do not edit */
#ifndef SOLARIAN_GFX_H
#define SOLARIAN_GFX_H

#define SOLARIAN_NTILE 280

/* tile indices, same layout as the NES version */
#define T_BLANK       0
#define T_ENEMY       68  /* + frame*4 (column-major) */
#define T_SHIP        96
#define T_MISSILE     100
#define T_BOMB        104
#define T_EXPLODE     112  /* + frame*4 */
#define T_FORM_SHIFT  256  /* + shift*3, 3 tiles each */
#define T_ENEMY_FLIP  128  /* + (frame*4+flip)*4 */

extern const unsigned char solarian_tiles[8960];

#endif
