
INPTCTRL        =     $01     ;Input control
AUDC0           =     $15     ;Audio Control Channel 0
AUDC1           =     $16     ;Audio Control Channel 1
AUDF0           =     $17     ;Audio Fr=ency Channel 0
AUDF1           =     $18     ;Audio Fr=ency Channel 1
AUDV0           =     $19     ;Audio Volume Channel 0
AUDV1           =     $1A     ;Audio Volume Channel 1
INPT0           =     $08     ;Paddle Control Input 0
INPT1           =     $09     ;Paddle Control Input 1
INPT2           =     $0A     ;Paddle Control Input 2
INPT3           =     $0B     ;Paddle Control Input 3
INPT4           =     $0C     ;Player 0 Fire Button Input
INPT5           =     $0D     ;Player 1 Fire Button Input

BACKGRND        =     $20     ;Background Color
P0C1            =     $21     ;Palette 0 - Color 1
P0C2            =     $22     ;Palette 0 - Color 2
P0C3            =     $23     ;Palette 0 - Color 3
WSYNC           =     $24     ;Wait For Sync
P1C1            =     $25     ;Palette 1 - Color 1
P1C2            =     $26     ;Palette 1 - Color 2
P1C3            =     $27     ;Palette 1 - Color 3
MSTAT           =     $28     ;Maria Status
P2C1            =     $29     ;Palette 2 - Color 1
P2C2            =     $2A     ;Palette 2 - Color 2
P2C3            =     $2B     ;Palette 2 - Color 3
DPPH            =     $2C     ;Display List List Pointer High
P3C1            =     $2D     ;Palette 3 - Color 1
P3C2            =     $2E     ;Palette 3 - Color 2
P3C3            =     $2F     ;Palette 3 - Color 3
DPPL            =     $30     ;Display List List Pointer Low
P4C1            =     $31     ;Palette 4 - Color 1
P4C2            =     $32     ;Palette 4 - Color 2
P4C3            =     $33     ;Palette 4 - Color 3
CHARBASE        =     $34     ;Character Base Address
P5C1            =     $35     ;Palette 5 - Color 1
P5C2            =     $36     ;Palette 5 - Color 2
P5C3            =     $37     ;Palette 5 - Color 3
OFFSET          =     $38     ;Unused - Store zero here
P6C1            =     $39     ;Palette 6 - Color 1
P6C2            =     $3A     ;Palette 6 - Color 2
P6C3            =     $3B     ;Palette 6 - Color 3
CTRL            =     $3C     ;Maria Control Register
P7C1            =     $3D     ;Palette 7 - Color 1
P7C2            =     $3E     ;Palette 7 - Color 2
P7C3            =     $3F     ;Palette 7 - Color 3

SWCHA           =     $280    ;P0, P1 Joystick Directional Input
SWCHB           =     $282    ;Console Switches
CTLSWA          =     $281    ;I/O Control for SCHWA
CTLSWB          =     $283    ;I/O Control for SCHWB
