;this file for FamiTone2 library generated by text2data tool
.export _music_data
_music_data:
	.byte 6
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env11
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env6,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env6,@env10
	.byte $00
	.byte $30 ;instrument $04
	.word @env1,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env3,@env8,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env8,@env10
	.byte $00
	.byte $30 ;instrument $08
	.word @env5,@env9,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $c7,$c5,$c4,$c3,$c3,$c2,$06,$c1,$0a,$c0,$00,$09
@env3:
	.byte $c6,$c6,$c5,$c4,$c3,$09,$c2,$08,$c1,$0f,$c0,$00,$0a
@env4:
	.byte $c8,$c3,$c2,$c1,$02,$c0,$00,$05
@env5:
	.byte $c5,$c5,$c4,$c4,$c3,$c0,$00,$05
@env6:
	.byte $c0,$c0,$c5,$c5,$c7,$c7,$00,$00
@env7:
	.byte $c6,$c3,$c0,$00,$02
@env8:
	.byte $c0,$02,$c4,$02,$c7,$c7,$c7,$00,$00
@env9:
	.byte $c6,$c6,$c0,$00,$02
@env10:
	.byte $c4,$00,$00
@env11:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$03
@ref0:
	.byte $8c,$33,$33,$36,$95
@song0ch0loop:
@ref1:
	.byte $9f
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref2:
	.byte $8e,$33,$33,$36,$95
@song0ch1loop:
@ref3:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref4:
	.byte $80,$33,$33,$90,$32,$80,$36,$83,$00,$8d
@song0ch2loop:
@ref5:
	.byte $9f
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref6:
	.byte $8a,$1f,$1f,$90,$17,$82,$1e,$91
@song0ch3loop:
@ref7:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref8:
	.byte $9f
@song0ch4loop:
@ref9:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$04
@song1ch0loop:
@ref10:
	.byte $9f
@ref11:
	.byte $9f
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
@ref16:
	.byte $9f
@ref17:
	.byte $9f
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref18:
	.byte $9f
@ref19:
	.byte $9f
@ref20:
	.byte $9f
@ref21:
	.byte $9f
@ref22:
	.byte $9f
@ref23:
	.byte $9f
@ref24:
	.byte $9f
@ref25:
	.byte $9f
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref26:
	.byte $80,$28,$00,$83,$28,$00,$27,$90,$32,$00,$8b
@ref27:
	.byte $80,$24,$00,$83,$25,$23,$90,$32,$00,$8b
@ref28:
	.byte $80,$28,$00,$83,$82,$28,$00,$27,$90,$32,$00,$83,$80,$26,$00,$83
@ref29:
	.byte $24,$00,$83,$25,$90,$32,$80,$22,$83,$00,$89
@ref30:
	.byte $28,$00,$83,$28,$00,$27,$90,$32,$00,$83,$80,$26,$00,$83
@ref31:
	.byte $24,$00,$83,$25,$23,$90,$32,$00,$8b
@ref32:
	.byte $80,$1e,$00,$83,$1e,$00,$23,$90,$32,$00,$83,$80,$25,$90,$32,$80
	.byte $28
@ref33:
	.byte $87,$00,$95
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref34:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$82,$1f,$8a,$1e,$81
@ref35:
	.byte $83,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$8a,$1e,$85
@ref36:
	.byte $1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$82,$1f,$8a,$1e,$81
@ref37:
	.byte $83,$1f,$82,$1f,$90,$16,$89,$8a,$1f,$1e,$81
	.byte $ff,$09
	.word @ref36
	.byte $ff,$08
	.word @ref35
@ref40:
	.byte $1f,$1f,$82,$1f,$8a,$1f,$90,$16,$85,$17,$16,$81
@ref41:
	.byte $87,$8a,$1f,$1f,$82,$1e,$85,$8a,$1f,$1e,$81
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref42:
	.byte $9f
@ref43:
	.byte $9f
@ref44:
	.byte $9f
@ref45:
	.byte $9f
@ref46:
	.byte $9f
@ref47:
	.byte $9f
@ref48:
	.byte $9f
@ref49:
	.byte $9f
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$03
@ref50:
	.byte $84,$3d,$3d,$3c,$85,$3d,$3d,$40,$a5
@song2ch0loop:
@ref51:
	.byte $bf
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref52:
	.byte $86,$3d,$3d,$3c,$85,$3d,$3d,$40,$a5
@song2ch1loop:
@ref53:
	.byte $bf
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref54:
	.byte $80,$3c,$00,$3c,$00,$3c,$00,$83,$3c,$00,$3c,$00,$88,$40,$8f,$00
	.byte $93
@song2ch2loop:
@ref55:
	.byte $bf
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref56:
	.byte $8a,$1f,$1f,$82,$1e,$85,$8a,$1f,$1f,$90,$17,$82,$1e,$a1
@song2ch3loop:
@ref57:
	.byte $bf
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref58:
	.byte $bf
@song2ch4loop:
@ref59:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@ref60:
	.byte $84,$24,$24,$83,$22,$22,$83,$20,$20,$83,$1f,$1a,$89,$32,$95
@song3ch0loop:
@ref61:
	.byte $bf
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref62:
	.byte $86,$24,$24,$83,$22,$22,$83,$20,$20,$83,$1f,$1a,$89,$32,$85,$32
	.byte $8d
@song3ch1loop:
@ref63:
	.byte $bf
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref64:
	.byte $80,$25,$01,$23,$01,$21,$01,$1f,$1a,$85,$01,$88,$32,$89,$00,$89
@song3ch2loop:
@ref65:
	.byte $bf
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref66:
	.byte $82,$1f,$8a,$1f,$82,$1d,$8a,$1f,$82,$1b,$8a,$1f,$82,$1b,$18,$89
	.byte $90,$17,$82,$1e,$91
@song3ch3loop:
@ref67:
	.byte $bf
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref68:
	.byte $bf
@song3ch4loop:
@ref69:
	.byte $bf
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$04
@song4ch0loop:
@ref70:
	.byte $84,$28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref71:
	.byte $24,$8d,$8c,$3c,$89,$3c,$89,$3c,$8d,$84,$24,$85
@ref72:
	.byte $28,$8d,$8c,$40,$89,$40,$89,$40,$8d,$84,$28,$85
@ref73:
	.byte $1a,$8d,$8c,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref74:
	.byte $86,$28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref75:
	.byte $24,$8d,$8e,$3c,$89,$3c,$89,$3c,$8d,$86,$24,$85
@ref76:
	.byte $28,$8d,$8e,$40,$89,$40,$89,$40,$8d,$86,$28,$85
@ref77:
	.byte $1a,$8d,$8e,$32,$89,$36,$89,$36,$95
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref78:
	.byte $80,$28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26
	.byte $00,$88,$29,$01,$80,$29,$22,$81
@ref79:
	.byte $24,$87,$00,$22,$00,$88,$25,$00,$85,$80,$25,$01,$25,$01,$22,$00
	.byte $25,$01,$25,$22,$81
@ref80:
	.byte $28,$87,$00,$26,$00,$88,$29,$00,$85,$80,$29,$01,$29,$01,$26,$00
	.byte $88,$29,$01,$80,$29,$00,$81
@ref81:
	.byte $32,$87,$00,$30,$00,$33,$00,$85,$37,$01,$37,$01,$34,$00,$88,$37
	.byte $01,$1f,$1e,$81
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref82:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$17,$8a,$1f,$82,$1e,$85
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref82
@ref85:
	.byte $8a,$1f,$1f,$82,$1f,$8a,$1f,$90,$17,$8a,$1f,$1f,$1f,$82,$1f,$8a
	.byte $1f,$1f,$1f,$90,$16,$85,$17,$16,$81
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$03
@ref90:
	.byte $84,$32,$8d,$2c,$85,$28,$a5
@song5ch0loop:
@ref91:
	.byte $bf
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@ref92:
	.byte $86,$32,$8d,$2c,$85,$28,$a5
@song5ch1loop:
@ref93:
	.byte $bf
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@ref94:
	.byte $88,$32,$85,$00,$85,$80,$2c,$85,$88,$2a,$95,$00,$8d
@song5ch2loop:
@ref95:
	.byte $bf
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@ref96:
	.byte $90,$16,$85,$8a,$1f,$1f,$1e,$85,$90,$16,$a5
@song5ch3loop:
@ref97:
	.byte $bf
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@ref98:
	.byte $bf
@song5ch4loop:
@ref99:
	.byte $bf
	.byte $fd
	.word @song5ch4loop
